<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Gross price as base price
    |--------------------------------------------------------------------------
    |
    | This default value is used to select the method to calculate prices and taxes
    | If true the item price is managed as a gross price, so taxes will be calculated by separation/exclusion
    |
    */

    'calculator' => App\Modules\Shop\Cart\DefaultCalculator::class,

    /*
    |--------------------------------------------------------------------------
    | Default tax rate
    |--------------------------------------------------------------------------
    |
    | This default tax rate will be used when you make a class implement the
    | Taxable interface and use the HasTax trait.
    |
    */

    'tax' => 22,

    /*
    |--------------------------------------------------------------------------
    | Tax estimate
    |--------------------------------------------------------------------------
    |
    | How the tax of a sale is estimated from the customer's billing data
    | (company VAT number, address country/state). The cart and the order show
    | the estimate; a gateway able to compute taxes (Stripe Tax, Paddle) may
    | replace it with the final amount.
    |   flat    : config('shop.tax') for everybody
    |   eu_vat  : the rules of a seller established in the EU (domestic rate,
    |             EU B2B reverse charge after a VIES check, customer-country
    |             rate for EU consumers, 0% outside the EU)
    |   a class : your own App\Modules\Shop\Tax\Contracts\TaxResolver
    |
    */
    'tax_resolver'   => env('SHOP_TAX_RESOLVER', 'flat'),
    'seller_country' => env('SHOP_SELLER_COUNTRY', 'IT'),
    'tax_rates'      => [],   // overrides of App\Modules\Shop\Tax\EuRates::STANDARD, e.g. ['IT' => 22]

    /*
    |--------------------------------------------------------------------------
    | Shoppingcart database settings
    |--------------------------------------------------------------------------
    |
    | Here you can set the connection that the shoppingcart should use when
    | storing and restoring a cart.
    |
    */

    'database' => [
        'connection' => 'default',
        'table' => 'carts',
    ],

    /*
    |--------------------------------------------------------------------------
    | Destroy the cart on user logout
    |--------------------------------------------------------------------------
    |
    | When this option is set to 'true' the cart will automatically
    | destroy all cart instances when the user logs out.
    |
    */

    'destroy_on_logout' => false,

    /*
    |--------------------------------------------------------------------------
    | Default number format
    |--------------------------------------------------------------------------
    |
    | This defaults will be used for the formatted numbers if you don't
    | set them in the method call.
    |
    */

    'format' => [

        'decimals' => 2,

        'decimal_point' => '.',

        'thousand_separator' => ',',

    ],

    'currency' => '€',

    'deliverable_types' => [
        'inventory_item' => App\Modules\Shop\Models\InventoryItem::class,
        'service_item'   => App\Modules\Shop\Models\ServiceItem::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Checkout mode
    |--------------------------------------------------------------------------
    |
    | 'immediate'        — customer can pay as soon as the order is created,
    |                      regardless of delivery-item assignment status.
    | 'after_assignment' — payment is blocked until all delivery items have
    |                      been assigned or generated by an admin/operator.
    |
    */
    'checkout_mode' => env('SHOP_CHECKOUT_MODE', 'immediate'),

    /*
    |--------------------------------------------------------------------------
    | Documents
    |--------------------------------------------------------------------------
    |
    | The documents the shop can hand out, by subject (the morph alias of the model):
    | a label and, optionally, the states of the subject they make sense in. The shop
    | shows a button for each one the bound DocumentRenderer supports
    | (App\Modules\Shop\Documents\Contracts\DocumentRenderer). No renderer is bound by
    | default: a documents module registers one (PDF, Excel…) with its templates.
    |
    */
    'documents' => [
        'order' => [
            'order_confirmation' => ['label' => 'Order confirmation', 'states' => ['payment_done', 'in_process', 'shipped', 'completed']],
            'delivery_note'      => ['label' => 'Delivery note',      'states' => ['shipped', 'completed']],
        ],
        'subscription' => [
            'subscription_statement' => ['label' => 'Statement'],
        ],
        'service_item' => [
            'license_certificate' => ['label' => 'Licence certificate', 'states' => ['active']],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Provisioning
    |--------------------------------------------------------------------------
    |
    | What happens to a sold service: a ServiceItem + licence per unit, driven by a
    | Provisioner (App\Modules\Shop\Provisioning\Contracts\Provisioner) chosen per
    | product (products.provisioner) among `drivers`; `default` when the product names
    | none. The `service_item` workflow (new → active → suspended / terminated) calls
    | the driver at every transition. Physical goods: assigned, shipped, then owned
    | by the customer when the order completes.
    |
    */
    'provisioning' => [
        'default'  => App\Modules\Shop\Provisioning\DefaultProvisioner::class,
        'drivers'  => [
            // 'myapp' => App\Provisioning\MyAppProvisioner::class,
        ],
        'auto_on_payment'  => env('SHOP_PROVISION_ON_PAYMENT', true),   // services of a paid order are generated (record + licence) at payment_done
        'require_shipping' => env('SHOP_REQUIRE_SHIPPING', true),       // an order with physical goods completes only once shipped
        'license_months'   => 12,                                       // licence of a service sold by an order

        // When a generated service is activated (the `provision` transition, which calls the driver):
        //   automatic  as soon as it is generated (a service the buyer uses: support, setup…)
        //   manual     by the operator (the "provision" button of the service item) or by your own code
        //   customer   by the end user, who redeems the licence key (B2B: sold to a reseller, activated by the final customer)
        // The default of the shop; a product can choose its own (products.activation).
        'activation' => env('SHOP_ACTIVATION', 'automatic'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Payment methods
    |--------------------------------------------------------------------------
    |
    | Classes implementing App\Modules\Shop\Payments\Contracts\PaymentMethod,
    | offered on the checkout page in this order. ManualPayment needs no
    | gateway: the order waits for an operator to confirm the payment.
    | zofe/payments-module adds its gateways (see gateway_methods) when installed.
    |
    */
    'payment_methods' => [
        App\Modules\Shop\Payments\ManualPayment::class,
    ],

    'manual_payment' => [
        'enabled'      => env('SHOP_MANUAL_PAYMENT', true),
        'label'        => 'Bank transfer',
        'description'  => 'We will send you the payment details',
        'icon'         => 'fa-university',
        // {description}, {total} and {email} are replaced
        'instructions' => 'Thank you. {description} ({total}) is registered: we will contact you at {email} with the payment details.',
    ],

    /*
    |--------------------------------------------------------------------------
    | Subscriptions
    |--------------------------------------------------------------------------
    | "Subscribe" on a product sold as a monthly / yearly fee creates a
    | Subscription with its items and the first pending payment; every period
    | `php artisan shop:bill-subscriptions` (daily) creates the next one. A
    | pending payment older than grace_days marks the subscription past due.
    */
    'subscriptions' => [
        'grace_days' => (int) env('SHOP_SUBSCRIPTION_GRACE_DAYS', 7),
    ],

    // Labels of the zofe/payments-module gateways on the checkout page
    'gateway_methods' => [
        'stripe' => [
            'label' => 'Credit / Debit Card',
            'description' => 'Pay securely via Stripe',
            'icon' => 'fa-credit-card',
        ],
        'paddle' => [
            'label' => 'Paddle',
            'description' => 'Pay via Paddle (MoR)',
            'icon' => 'fa-shopping-bag',
        ],
        'gocardless' => [
            'label' => 'Direct Debit',
            'description' => 'Pay via GoCardless bank debit',
            'icon' => 'fa-university',
        ],
    ],

];
