<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Gross price as base price
    |--------------------------------------------------------------------------
    |
    | This default value is used to select the method to calculate prices and taxes
    | If true the item price is managed as a gross price, so taxes will be calculated by separation/exclusion
    |
    */

    'calculator' => App\Modules\Shop\Cart\DefaultCalculator::class,

    /*
    |--------------------------------------------------------------------------
    | Default tax rate
    |--------------------------------------------------------------------------
    |
    | This default tax rate will be used when you make a class implement the
    | Taxable interface and use the HasTax trait.
    |
    */

    'tax' => 22,

    /*
    |--------------------------------------------------------------------------
    | Tax estimate
    |--------------------------------------------------------------------------
    |
    | How the tax of a sale is estimated from the customer's billing data
    | (company VAT number, address country/state). The cart and the order show
    | the estimate; a gateway able to compute taxes (Stripe Tax, Paddle) may
    | replace it with the final amount.
    |   flat    : config('shop.tax') for everybody
    |   eu_vat  : the rules of a seller established in the EU (domestic rate,
    |             EU B2B reverse charge after a VIES check, customer-country
    |             rate for EU consumers, 0% outside the EU)
    |   a class : your own App\Modules\Shop\Tax\Contracts\TaxResolver
    |
    */
    'tax_resolver'   => env('SHOP_TAX_RESOLVER', 'flat'),
    'seller_country' => env('SHOP_SELLER_COUNTRY', 'IT'),
    'tax_rates'      => [],   // overrides of App\Modules\Shop\Tax\EuRates::STANDARD, e.g. ['IT' => 22]

    /*
    |--------------------------------------------------------------------------
    | Shoppingcart database settings
    |--------------------------------------------------------------------------
    |
    | Here you can set the connection that the shoppingcart should use when
    | storing and restoring a cart.
    |
    */

    'database' => [
        'connection' => 'default',
        'table' => 'carts',
    ],

    /*
    |--------------------------------------------------------------------------
    | Destroy the cart on user logout
    |--------------------------------------------------------------------------
    |
    | When this option is set to 'true' the cart will automatically
    | destroy all cart instances when the user logs out.
    |
    */

    'destroy_on_logout' => false,

    /*
    |--------------------------------------------------------------------------
    | Default number format
    |--------------------------------------------------------------------------
    |
    | This defaults will be used for the formatted numbers if you don't
    | set them in the method call.
    |
    */

    'format' => [

        'decimals' => 2,

        'decimal_point' => '.',

        'thousand_separator' => ',',

    ],

    'currency' => '€',

    'deliverable_types' => [
        'inventory_item' => App\Modules\Shop\Models\InventoryItem::class,
        'service_item'   => App\Modules\Shop\Models\ServiceItem::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Payment gateways available at checkout
    |--------------------------------------------------------------------------
    |
    | Each entry maps a gateway key (used by payments-module) to its display label and icon.
    |
    */
    /*
    |--------------------------------------------------------------------------
    | Checkout mode
    |--------------------------------------------------------------------------
    |
    | 'immediate'        — customer can pay as soon as the order is created,
    |                      regardless of delivery-item assignment status.
    | 'after_assignment' — payment is blocked until all delivery items have
    |                      been assigned or generated by an admin/operator.
    |
    */
    'checkout_mode' => env('SHOP_CHECKOUT_MODE', 'immediate'),

    'payment_gateways' => [
        'stripe' => [
            'label' => 'Credit / Debit Card',
            'description' => 'Pay securely via Stripe',
            'icon' => 'fa-credit-card',
        ],
        'paddle' => [
            'label' => 'Paddle',
            'description' => 'Pay via Paddle (MoR)',
            'icon' => 'fa-shopping-bag',
        ],
        'gocardless' => [
            'label' => 'Direct Debit',
            'description' => 'Pay via GoCardless bank debit',
            'icon' => 'fa-university',
        ],
    ],

];
